-
  uid: CHE-109.740.084
  name: Baloise-Sammelstiftung fuer die obligatorische berufliche Vorsorge
  idPartner:
  cdStf: 1
-
  uid: CHE-223.471.073
  name: Perspectiva Sammelstiftung fuer berufliche Vorsorge
  idPartner:
  cdStf: 4
-
  uid: CHE-109.537.519
  name: Helvetia-Sammelstiftung
  idPartner: 60000201
  cdStf: 0
