[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology Decisions

In the team we've decided to use the following technologies:

* Language: Java 8
* Framework: link:https://spring.io/projects/spring-boot[Spring Boot]
* REST API
** link:https://swagger.io/specification/[OpenAPI] Swagger for documentation
* used during development
** link:https://www.docker.com/open-source[Docker container] for integration testing
** link:https://www.eclipse.org/openj9/[OpenJ9]-JVM