language: java
sudo: required
services:
  - docker
deploy:
  provider: releases
  api_key:
    secure: hLJXiN/gP/wKtknj6A0HEgS54luVwn78vn+Cn/03xTBx+mVt98vvEtguIrpSzgltZS7mxLNnnF+Gd5KeVQSGTB8kcBijbiGsNQn6rzcr26MbBIGecEZydQSx87Uncly+rssUo8u1bx8GsO1Z4lhvSN/UU6MaqjRQnO7zrT6ju+4VqzEh/+6xHQqYN8XYTbAKlNGmBkp5qCnLVqGUvP3WHeOgx3046AmnVxX0jI81EbuEvbbQa+rByjCqMUXbIlWZkJWKFLVVvrOZdqe5tUOCK++TrVZajPq1FqCDuD/N8DjK60YCVx60lq3gvflTVmIQVFDJQ63Nrumy87NrXHxOmi8YVwMfYXB+ILJzdSWeKaR7iAe1zGtpfSdRidbCZbIOX/XHEOxcTnyZlJFtfQ7a1WRMtG8Rx16rPORjBwNO3c2Drwhd+u+2LVv5pujFSSMeLf1rx6DzDi9qgrWZX9RlNt7WRTJggFs4hFWb69K9OoI+hWnT61VEwBe9sn8CfdstErx2Y+wRWbCgc50y1cI4fnbsIQWv6YjIc4C5xpfiZCUAvO+/ACvCI3G6iLYjS/9KIvf1BlOwpMx7lwdY2QpdDJ7MBTQVFuh6S/lr5ickgSgJ9ru2etzYtK7wRr1vERvvY2TR9bii0Z3HHpsRt9wR0gmwJejzfBxopWydP15WREw=
  file: 
    - "demo/build/demo.zip"
    - "doc/build/doc.zip"
  skip_cleanup: true
  on:
    tags: true
    repo: open-prevo/openprevo
