version: '2'
services:
  node_baloise:
    image: "openprevo/node-dummy:staging"
    hostname: baloise
    ports:
    - "8881:8080"
  node_helvetia:
    image: "openprevo/node-dummy:staging"
    hostname: helvetia
    ports:
    - "8882:8080"
    environment:
      EMPLOYMENT_COMMENCEMENT_JSON: "classpath:pakt-sample-employment-commencement.json"
      EMPLOYMENT_TERMINATION_JSON: "classpath:pakt-sample-employment-termination.json"